platform :ios, "7.0"

pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'

#Production pod
#pod 'QMCVDevelopment', :git => 'https://github.com/QuickBlox/QMChatViewController-ios', :tag => '0.2.5'
pod 'QMChatViewController'

#Production pod
#pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'
pod 'QMServices'

pod 'SDWebImage', '~>3.7'

pod 'mailcore2-ios'
